DROP TABLE CLIENTES IF EXISTS;

CREATE TABLE CLIENTES (
    Dni INT NOT NULL,
    Nombre VARCHAR(150) NOT NULL,
    Apellido VARCHAR(150) NOT NULL,
    FechaDeNacimiento DATE NOT NULL,
    PRIMARY KEY (Dni)
);